# Generated by Django 3.0.1 on 2019-12-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_post_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_location',
            new_name='post_image',
        ),
    ]
