# Generated by Django 3.0 on 2019-12-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191228_2158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'batch_year')},
        ),
    ]
