# Generated by Django 3.0 on 2019-12-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191228_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=300)),
            ],
        ),
    ]
