# Generated by Django 3.0 on 2019-12-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_libray'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libray',
            new_name='Library',
        ),
    ]
