# Generated by Django 3.0 on 2019-12-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191228_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_title', models.CharField(max_length=300)),
                ('reference_description', models.TextField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Library')),
            ],
        ),
    ]
