# Generated by Django 3.0 on 2019-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191228_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_status', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Post Statuses',
            },
        ),
    ]
