# Generated by Django 3.0 on 2019-12-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_poststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PostStatus'),
        ),
    ]
