# Generated by Django 3.0 on 2019-12-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191229_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_status',
            new_name='poststatus',
        ),
    ]
