# Generated by Django 3.0 on 2019-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191229_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_image',
            field=models.ImageField(blank='TRUE', null='TRUE', upload_to='uploads/'),
        ),
    ]
