# Generated by Django 3.0 on 2019-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191230_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_attachment',
            field=models.FileField(blank='TRUE', null='TRUE', upload_to='uploads/'),
        ),
    ]
