# Generated by Django 3.0 on 2020-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200101_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_abv',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
