# Generated by Django 3.0 on 2020-01-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200101_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_image',
            field=models.ImageField(null='TRUE', upload_to='uploads/'),
            preserve_default='TRUE',
        ),
        migrations.CreateModel(
            name='BatchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_image_description', models.CharField(max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Batch')),
            ],
        ),
    ]
