# Generated by Django 3.0 on 2020-01-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200109_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='reference_attachment',
        ),
    ]
