# Generated by Django 3.0 on 2020-01-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_reference_reference_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_attachment',
            field=models.FileField(null='TRUE', upload_to='uploads'),
            preserve_default='TRUE',
        ),
    ]
