# Generated by Django 3.0 on 2020-01-11 07:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200111_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
