# Generated by Django 3.0 on 2020-01-12 03:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200111_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_title', models.CharField(max_length=300)),
                ('tab_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tab_image', models.ImageField(null='TRUE', upload_to='uploads/')),
            ],
        ),
    ]
